# Generated by Django 4.2.13 on 2024-07-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_contact_contact_id_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
